### ISSUE TITLE
How could this work inside Play Framework

### ISSUE THREAD

**Issue by PhilAndrew** [outr/youi#30]
Lets say I am using Play Framework and I want to somehow embed this inside my Play application, how could it be done?

**Comment by darkfrog26** [comment]
Doesn't play only work on Netty now?

**Comment by PhilAndrew** [comment]
Yes Netty. Ignoring Netty, apart from that I was trying to think how I would want to use it with Play. I would want to place some sort of tag into the play app page and then your hyperscala app could appear where that tag was.

Play html template (page.scala.html) https://www.playframework.com/documentation/2.4.x/ScalaTemplates

Scala helpers https://www.playframework.com/documentation/2.4.x/Home

ie. if I had a page.scala.html it would look like this with a helper which would make your code appear:

    <some><html>
    @someFunctionInjectsYourCodeAndAppearsOnPage()
    </html></some>

There would have to be some helper to inject into the header as well.

I think this is something I could consider to do as a side project.

**Comment by darkfrog26** [comment]
In order for Hyperscala and Play to work together you'd need to have support for Netty in outrnet. It used to support it, but the integration is broken.  Take a look at https://github.com/darkfrog26/outrnet if you'd like to try your hand implementing it (if you know Netty it shouldn't be very difficult).

What libraries does Play offer better integration with?
